/** 핵심 39종 — speciesId → AI slug (export·인증·랭킹 고정) */
export const CURATED_SPECIES_SLUGS: Record<number, string> = {
  1: 'largemouth_bass',
  2: 'mandarin_fish',
  3: 'snakehead',
  4: 'crucian_carp',
  5: 'common_carp',
  6: 'amur_catfish',
  7: 'japanese_eel',
  8: 'red_seabream',
  9: 'olive_flounder',
  10: 'korean_rockfish',
  11: 'black_porgy',
  12: 'japanese_seabass',
  13: 'japanese_amberjack',
  14: 'chub_mackerel',
  15: 'japanese_spanish_mackerel',
  16: 'korean_loach',
  17: 'ayu',
  18: 'rainbow_trout',
  19: 'freshwater_minnow',
  20: 'korean_sharpbelly',
  21: 'icefish',
  22: 'masu_salmon',
  23: 'japanese_scad',
  24: 'pike_eel',
  25: 'flathead_mullet',
  26: 'silver_croaker',
  27: 'brown_croaker',
  28: 'striped_beakfish',
  29: 'goldlined_seabream',
  30: 'nugget_rockfish',
  31: 'cortez_halibut',
  32: 'japanese_whiting',
  33: 'largehead_hairtail',
  34: 'pacific_cod',
  35: 'alaska_pollock',
  36: 'stone_flounder',
  37: 'skipjack',
  38: 'skygazer',
  39: 'bluegill',
};

/** 구형 AI slug 호환 */
export const SPECIES_SLUG_ALIASES: Record<string, string> = {
  bass: 'largemouth_bass',
  catfish: 'amur_catfish',
  flounder: 'olive_flounder',
  rockfish: 'korean_rockfish',
};
