export type FishCategory = 'freshwater' | 'saltwater' | 'brackish';

export type FishCatalogEntry = {
  speciesId: number;
  nameKo: string;
  nameEn: string;
  /** iNaturalist 학명 (정확 매칭용) */
  scientificName: string;
  /** iNaturalist taxon ID — 있으면 우선 사용 */
  iNaturalistTaxonId?: number;
  category: FishCategory;
  rarityWeight: number;
  /** 공공데이터포털 국명 검색어 */
  publicDataQuery: string;
  season?: string;
  bait?: string;
  technique?: string;
  minSizeLaw?: number;
  avgLengthCm?: number;
  maxLengthCm?: number;
};

/**
 * 국내 낚시 대상 어종 카탈로그 (민물·바다·기수)
 * - iNaturalist: 학명/taxonId 고정 매칭 (autocomplete 오매칭 방지)
 * - 공공데이터포털: 국명 검색 + 결과 검증
 */
export const FISH_CATALOG: FishCatalogEntry[] = [
  // ── 민물 ──
  {
    speciesId: 1,
    nameKo: '배스',
    nameEn: 'Largemouth Bass',
    scientificName: 'Micropterus salmoides',
    iNaturalistTaxonId: 49587,
    category: 'freshwater',
    rarityWeight: 1.0,
    publicDataQuery: '배스',
    season: '4월~11월 (5~6월 성수기)',
    bait: '지그헤드, 스피너베이트, 웜, 크랭크베이트',
    technique: '루어낚시 (배스피싱)',
    avgLengthCm: 35,
    maxLengthCm: 65,
  },
  {
    speciesId: 2,
    nameKo: '쏘가리',
    nameEn: 'Mandarin Fish',
    scientificName: 'Siniperca scherzeri',
    iNaturalistTaxonId: 128285,
    category: 'freshwater',
    rarityWeight: 1.5,
    publicDataQuery: '쏘가리',
    season: '4월~10월',
    bait: '생새우, 지렁이, 소형 미노우',
    technique: '채비낚시, 루어낚시',
    avgLengthCm: 30,
    maxLengthCm: 60,
  },
  {
    speciesId: 3,
    nameKo: '가물치',
    nameEn: 'Snakehead',
    scientificName: 'Channa argus',
    iNaturalistTaxonId: 128487,
    category: 'freshwater',
    rarityWeight: 1.3,
    publicDataQuery: '가물치',
    season: '5월~10월',
    bait: '개구리, 대형 루어, 생미끼',
    technique: '루어낚시, 생미끼낚시',
    avgLengthCm: 60,
    maxLengthCm: 100,
  },
  {
    speciesId: 4,
    nameKo: '붕어',
    nameEn: 'Crucian Carp',
    scientificName: 'Carassius carassius',
    category: 'freshwater',
    rarityWeight: 1.0,
    publicDataQuery: '붕어',
    season: '연중 (봄·가을 성수기)',
    bait: '지렁이, 옥수수, 글루텐',
    technique: '찌낚시, 떡밥낚시',
    avgLengthCm: 25,
    maxLengthCm: 45,
  },
  {
    speciesId: 5,
    nameKo: '잉어',
    nameEn: 'Common Carp',
    scientificName: 'Cyprinus carpio',
    category: 'freshwater',
    rarityWeight: 1.1,
    publicDataQuery: '잉어',
    season: '4월~10월',
    bait: '옥수수, 떡밥, 보릿가루',
    technique: '찌낚시, 원투',
    avgLengthCm: 40,
    maxLengthCm: 90,
  },
  {
    speciesId: 6,
    nameKo: '메기',
    nameEn: 'Amur Catfish',
    scientificName: 'Silurus asotus',
    category: 'freshwater',
    rarityWeight: 1.2,
    publicDataQuery: '메기',
    season: '6월~9월',
    bait: '지렁이, 생선, 오징어',
    technique: '밑밥낚시, 원투',
    avgLengthCm: 50,
    maxLengthCm: 100,
  },
  {
    speciesId: 7,
    nameKo: '뱀장어',
    nameEn: 'Japanese Eel',
    scientificName: 'Anguilla japonica',
    category: 'brackish',
    rarityWeight: 1.6,
    publicDataQuery: '뱀장어',
    season: '7월~11월',
    bait: '지렁이, 오징어, 생미끼',
    technique: '민장대, 갯바위·하구',
    avgLengthCm: 50,
    maxLengthCm: 100,
  },
  {
    speciesId: 16,
    nameKo: '미꾸라지',
    nameEn: 'Korean Loach',
    scientificName: 'Misgurnus mizolepis',
    category: 'freshwater',
    rarityWeight: 1.0,
    publicDataQuery: '미꾸라지',
    season: '5월~9월',
    bait: '지렁이, 떡밥',
    technique: '찌낚시, 민물 바닥',
    avgLengthCm: 12,
    maxLengthCm: 25,
  },
  {
    speciesId: 17,
    nameKo: '향어',
    nameEn: 'Ayu',
    scientificName: 'Plecoglossus altivelis',
    category: 'freshwater',
    rarityWeight: 1.4,
    publicDataQuery: '향어',
    season: '6월~9월',
    bait: '인공 미꾸, 루어',
    technique: '향어낚시, 루어',
    avgLengthCm: 20,
    maxLengthCm: 30,
  },
  {
    speciesId: 18,
    nameKo: '송어',
    nameEn: 'Rainbow Trout',
    scientificName: 'Oncorhynchus mykiss',
    category: 'freshwater',
    rarityWeight: 1.2,
    publicDataQuery: '송어',
    season: '10월~3월 (겨울 성수기)',
    bait: '스푼, 파워베이트, 인공파리',
    technique: '루어, 인공파리',
    avgLengthCm: 30,
    maxLengthCm: 60,
  },
  {
    speciesId: 19,
    nameKo: '피라미',
    nameEn: 'Freshwater Minnow',
    scientificName: 'Zacco platypus',
    category: 'freshwater',
    rarityWeight: 0.9,
    publicDataQuery: '피라미',
    season: '4월~10월',
    bait: '작은 지렁이, 떡밥',
    technique: '찌낚시',
    avgLengthCm: 12,
    maxLengthCm: 22,
  },
  {
    speciesId: 20,
    nameKo: '메운',
    nameEn: 'Korean Sharpbelly',
    scientificName: 'Hemiculter eigenmanni',
    category: 'freshwater',
    rarityWeight: 0.9,
    publicDataQuery: '메운',
    season: '5월~9월',
    bait: '작은 지렁이, 떡밥',
    technique: '찌낚시',
    avgLengthCm: 10,
    maxLengthCm: 18,
  },
  {
    speciesId: 21,
    nameKo: '빙어',
    nameEn: 'Icefish',
    scientificName: 'Salangichthys microdon',
    category: 'freshwater',
    rarityWeight: 1.0,
    publicDataQuery: '빙어',
    season: '12월~2월',
    bait: '지렁이, 붕어알',
    technique: '얼음낚시',
    avgLengthCm: 10,
    maxLengthCm: 15,
  },
  {
    speciesId: 22,
    nameKo: '산천어',
    nameEn: 'Masu Salmon',
    scientificName: 'Oncorhynchus masou',
    category: 'freshwater',
    rarityWeight: 1.5,
    publicDataQuery: '산천어',
    season: '5월~10월',
    bait: '인공파리, 스푼',
    technique: '루어, 인공파리',
    avgLengthCm: 35,
    maxLengthCm: 70,
  },
  {
    speciesId: 38,
    nameKo: '강준치',
    nameEn: 'Skygazer',
    scientificName: 'Erythroculter erythropterus',
    category: 'freshwater',
    rarityWeight: 1.6,
    publicDataQuery: '강준치',
    season: '4월~10월 (5~6월 성수기)',
    bait: '크랭크베이트, 미노우, 스푼',
    technique: '루어낚시 (한강·금강·낙동강 하류)',
    avgLengthCm: 50,
    maxLengthCm: 100,
  },

  // ── 바다 ──
  {
    speciesId: 8,
    nameKo: '참돔',
    nameEn: 'Red Seabream',
    scientificName: 'Pagrus major',
    iNaturalistTaxonId: 132534,
    category: 'saltwater',
    rarityWeight: 1.8,
    publicDataQuery: '참돔',
    season: '연중 (봄·가을 성수기)',
    bait: '갯지렁이, 새우, 어분',
    technique: '선상, 찌낚시',
    minSizeLaw: 24,
    avgLengthCm: 40,
    maxLengthCm: 80,
  },
  {
    speciesId: 11,
    nameKo: '감성돔',
    nameEn: 'Black Porgy',
    scientificName: 'Acanthopagrus schlegelii',
    category: 'saltwater',
    rarityWeight: 1.7,
    publicDataQuery: '감성돔',
    season: '10월~3월',
    bait: '게, 갯지렁이, 크릴',
    technique: '찌낚시, 바닥낚시',
    minSizeLaw: 25,
    avgLengthCm: 35,
    maxLengthCm: 65,
  },
  {
    speciesId: 10,
    nameKo: '우럭',
    nameEn: 'Korean Rockfish',
    scientificName: 'Sebastes schlegelii',
    iNaturalistTaxonId: 620538,
    category: 'saltwater',
    rarityWeight: 1.2,
    publicDataQuery: '우럭',
    season: '연중',
    bait: '갯지렁이, 오징어',
    technique: '찌낚시, 갯바위',
    avgLengthCm: 30,
    maxLengthCm: 50,
  },
  {
    speciesId: 30,
    nameKo: '볼락',
    nameEn: 'Nugget Rockfish',
    scientificName: 'Sebastes inermis',
    category: 'saltwater',
    rarityWeight: 1.0,
    publicDataQuery: '볼락',
    season: '연중',
    bait: '갯지렁이, 오징어',
    technique: '찌낚시, 갯바위',
    avgLengthCm: 20,
    maxLengthCm: 35,
  },
  {
    speciesId: 14,
    nameKo: '고등어',
    nameEn: 'Chub Mackerel',
    scientificName: 'Scomber japonicus',
    category: 'saltwater',
    rarityWeight: 0.8,
    publicDataQuery: '고등어',
    season: '9월~12월',
    bait: '피칭 루어, 살치',
    technique: '선상, 캐스팅',
    avgLengthCm: 35,
    maxLengthCm: 55,
  },
  {
    speciesId: 9,
    nameKo: '광어',
    nameEn: 'Olive Flounder',
    scientificName: 'Paralichthys olivaceus',
    iNaturalistTaxonId: 361763,
    category: 'saltwater',
    rarityWeight: 1.6,
    publicDataQuery: '광어',
    season: '연중 (겨울 성수기)',
    bait: '생미끼, 소형 루어',
    technique: '선상, 루어',
    minSizeLaw: 35,
    avgLengthCm: 45,
    maxLengthCm: 90,
  },
  {
    speciesId: 12,
    nameKo: '농어',
    nameEn: 'Japanese Seabass',
    scientificName: 'Lateolabrax japonicus',
    category: 'saltwater',
    rarityWeight: 1.5,
    publicDataQuery: '농어',
    season: '봄·가을',
    bait: '생미끼, 루어, 지렁이',
    technique: '루어, 찌낚시',
    avgLengthCm: 40,
    maxLengthCm: 80,
  },
  {
    speciesId: 13,
    nameKo: '방어',
    nameEn: 'Japanese Amberjack',
    scientificName: 'Seriola quinqueradiata',
    category: 'saltwater',
    rarityWeight: 2.0,
    publicDataQuery: '방어',
    season: '10월~1월',
    bait: '전갱이, 고등어 (활미끼)',
    technique: '지깅, 캐스팅, 선상',
    avgLengthCm: 70,
    maxLengthCm: 150,
  },
  {
    speciesId: 15,
    nameKo: '삼치',
    nameEn: 'Japanese Spanish Mackerel',
    scientificName: 'Scomberomorus niphonius',
    category: 'saltwater',
    rarityWeight: 1.3,
    publicDataQuery: '삼치',
    season: '6월~10월',
    bait: '피칭 루어, 살치',
    technique: '캐스팅, 선상',
    avgLengthCm: 60,
    maxLengthCm: 100,
  },
  {
    speciesId: 23,
    nameKo: '전갱이',
    nameEn: 'Japanese Scad',
    scientificName: 'Decapterus maruadsi',
    iNaturalistTaxonId: 473385,
    category: 'saltwater',
    rarityWeight: 0.9,
    publicDataQuery: '전갱이',
    season: '6월~10월',
    bait: '작은 생미끼, 루어',
    technique: '선상, 갯바위',
    avgLengthCm: 25,
    maxLengthCm: 40,
  },
  {
    speciesId: 24,
    nameKo: '붕장어',
    nameEn: 'Pike Eel',
    scientificName: 'Muraenesox cinereus',
    category: 'saltwater',
    rarityWeight: 1.3,
    publicDataQuery: '붕장어',
    season: '5월~10월',
    bait: '오징어, 생선',
    technique: '갯바위, 선상',
    avgLengthCm: 80,
    maxLengthCm: 150,
  },
  {
    speciesId: 25,
    nameKo: '숭어',
    nameEn: 'Flathead Mullet',
    scientificName: 'Mugil cephalus',
    category: 'brackish',
    rarityWeight: 1.0,
    publicDataQuery: '숭어',
    season: '11월~2월',
    bait: '떡밥, 빵, 지렁이',
    technique: '찌낚시, 하구',
    avgLengthCm: 35,
    maxLengthCm: 60,
  },
  {
    speciesId: 26,
    nameKo: '조기',
    nameEn: 'Silver Croaker',
    scientificName: 'Pennahia argentata',
    category: 'saltwater',
    rarityWeight: 1.1,
    publicDataQuery: '조기',
    season: '9월~12월',
    bait: '갯지렁이, 오징어',
    technique: '선상, 찌낚시',
    avgLengthCm: 25,
    maxLengthCm: 45,
  },
  {
    speciesId: 27,
    nameKo: '민어',
    nameEn: 'Brown Croaker',
    scientificName: 'Miichthys miiuy',
    iNaturalistTaxonId: 620347,
    category: 'saltwater',
    rarityWeight: 1.4,
    publicDataQuery: '민어',
    season: '6월~10월',
    bait: '갯지렁이, 생미끼',
    technique: '선상, 찌낚시',
    avgLengthCm: 50,
    maxLengthCm: 120,
  },
  {
    speciesId: 28,
    nameKo: '돌돔',
    nameEn: 'Striped Beakfish',
    scientificName: 'Oplegnathus fasciatus',
    category: 'saltwater',
    rarityWeight: 1.5,
    publicDataQuery: '돌돔',
    season: '연중',
    bait: '갯지렁이, 새우',
    technique: '갯바위, 찌낚시',
    avgLengthCm: 35,
    maxLengthCm: 60,
  },
  {
    speciesId: 29,
    nameKo: '범돔',
    nameEn: 'Goldlined Seabream',
    scientificName: 'Rhabdosargus sarba',
    category: 'saltwater',
    rarityWeight: 1.3,
    publicDataQuery: '범돔',
    season: '연중',
    bait: '갯지렁이, 떡밥',
    technique: '찌낚시, 갯바위',
    avgLengthCm: 30,
    maxLengthCm: 50,
  },
  {
    speciesId: 31,
    nameKo: '도다리',
    nameEn: 'Cortez Halibut',
    scientificName: 'Pleuronichthys cornutus',
    category: 'saltwater',
    rarityWeight: 1.1,
    publicDataQuery: '도다리',
    season: '봄·가을',
    bait: '갯지렁이, 오징어',
    technique: '갯바위, 찌낚시',
    avgLengthCm: 20,
    maxLengthCm: 35,
  },
  {
    speciesId: 32,
    nameKo: '백조기',
    nameEn: 'Japanese Whiting',
    scientificName: 'Sillago parvisquamis',
    category: 'saltwater',
    rarityWeight: 1.0,
    publicDataQuery: '백조기',
    season: '5월~10월',
    bait: '갯지렁이, 오징어',
    technique: '찌낚시, 갯바위',
    avgLengthCm: 20,
    maxLengthCm: 35,
  },
  {
    speciesId: 33,
    nameKo: '갈치',
    nameEn: 'Largehead Hairtail',
    scientificName: 'Trichiurus lepturus',
    category: 'saltwater',
    rarityWeight: 1.4,
    publicDataQuery: '갈치',
    season: '7월~12월',
    bait: '오징어, 생선',
    technique: '선상, 갯바위',
    avgLengthCm: 80,
    maxLengthCm: 150,
  },
  {
    speciesId: 34,
    nameKo: '대구',
    nameEn: 'Pacific Cod',
    scientificName: 'Gadus macrocephalus',
    category: 'saltwater',
    rarityWeight: 1.3,
    publicDataQuery: '대구',
    season: '12월~2월',
    bait: '오징어, 생선',
    technique: '선상, 얼음낚시',
    avgLengthCm: 50,
    maxLengthCm: 100,
  },
  {
    speciesId: 35,
    nameKo: '명태',
    nameEn: 'Alaska Pollock',
    scientificName: 'Gadus chalcogrammus',
    category: 'saltwater',
    rarityWeight: 1.0,
    publicDataQuery: '명태',
    season: '12월~2월',
    bait: '오징어, 생미끼',
    technique: '선상, 얼음낚시',
    avgLengthCm: 40,
    maxLengthCm: 70,
  },
  {
    speciesId: 36,
    nameKo: '가자미',
    nameEn: 'Stone Flounder',
    scientificName: 'Kareius bicoloratus',
    category: 'saltwater',
    rarityWeight: 1.1,
    publicDataQuery: '가자미',
    season: '봄·가을',
    bait: '갯지렁이, 오징어',
    technique: '갯바위, 찌낚시',
    avgLengthCm: 25,
    maxLengthCm: 45,
  },
  {
    speciesId: 37,
    nameKo: '학공치',
    nameEn: 'Skipjack',
    scientificName: 'Katsuwonus pelamis',
    category: 'saltwater',
    rarityWeight: 1.2,
    publicDataQuery: '학공치',
    season: '7월~10월',
    bait: '피칭 루어',
    technique: '선상, 캐스팅',
    avgLengthCm: 50,
    maxLengthCm: 80,
  },
];

export const FISH_CATALOG_OTHER: FishCatalogEntry = {
  speciesId: 99,
  nameKo: '기타',
  nameEn: 'Other',
  scientificName: '',
  category: 'freshwater',
  rarityWeight: 1.0,
  publicDataQuery: '기타',
};

export const ALL_FISH_CATALOG = [...FISH_CATALOG, FISH_CATALOG_OTHER];

export function getCatalogEntry(speciesId: number): FishCatalogEntry | undefined {
  return ALL_FISH_CATALOG.find((s) => s.speciesId === speciesId);
}

export function getCatalogByCategory(category: FishCategory | 'all') {
  if (category === 'all') return FISH_CATALOG;
  if (category === 'brackish') return FISH_CATALOG.filter((s) => s.category === 'brackish');
  return FISH_CATALOG.filter((s) => s.category === category);
}

export const FISH_CATALOG_STATS = {
  total: FISH_CATALOG.length,
  freshwater: FISH_CATALOG.filter((s) => s.category === 'freshwater').length,
  saltwater: FISH_CATALOG.filter((s) => s.category === 'saltwater').length,
  brackish: FISH_CATALOG.filter((s) => s.category === 'brackish').length,
};
